# Generated by Django 4.2.13 on 2024-06-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_desired_trades_alter_item_may_contain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
