# Generated by Django 4.2.13 on 2024-05-30 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0003_alter_item_desired_trades_alter_item_may_contain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='pending', max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item_offered', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_request', to='items.item')),
                ('item_requested', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_in_request', to='items.item')),
                ('receiver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_request', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
