# Generated by Django 4.2.13 on 2024-06-06 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='item_offered',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_requests', to='items.item'),
        ),
        migrations.AlterField(
            model_name='request',
            name='item_requested',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_in_requests', to='items.item'),
        ),
        migrations.AlterField(
            model_name='request',
            name='receiver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='sender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
